name    'guilhermef-supervisor'
version '0.0.1'
author 'Digg, Inc'
license 'UNKNOWN'
summary 'Supervisor module made by Digg, Inc'
description 'Supervisor module made by Digg, Inc https://github.com/plathrop/puppet-module-supervisor'
project_page 'https://github.com/plathrop/puppet-module-supervisor'
